import { ROLES } from '../constants/roles.js';

export const FEATURES = Object.freeze({
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',
  USER_ADMIN: 'USER_ADMIN',
  CONFIG_ADMIN: 'CONFIG_ADMIN',
  PURCHASE_VIEW: 'PURCHASE_VIEW',
  FINANCE_VIEW: 'FINANCE_VIEW'
});

export const ROUTE_KEYS = Object.freeze({
  HOME: 'HOME',
  CUSTOMERS: 'CUSTOMERS',
  SALES: 'SALES',
  INVENTORY: 'INVENTORY',
  PURCHASE: 'PURCHASE',
  FINANCE: 'FINANCE',
  REPORTS: 'REPORTS',
  ME: 'ME',
  ADMIN_USERS: 'ADMIN_USERS',
  ADMIN_CONFIG: 'ADMIN_CONFIG'
});

export const ROLE_PERMS = Object.freeze({
  [ROLES.SUPER_ADMIN]: {
    routes: Object.values(ROUTE_KEYS),
    features: Object.values(FEATURES)
  },
  [ROLES.SALES_DIRECTOR]: {
    routes: [ROUTE_KEYS.HOME, ROUTE_KEYS.CUSTOMERS, ROUTE_KEYS.SALES, ROUTE_KEYS.REPORTS, ROUTE_KEYS.ME],
    features: []
  },
  [ROLES.SALES]: {
    routes: [ROUTE_KEYS.HOME, ROUTE_KEYS.CUSTOMERS, ROUTE_KEYS.SALES, ROUTE_KEYS.REPORTS, ROUTE_KEYS.ME],
    features: []
  },
  [ROLES.WAREHOUSE]: {
    routes: [ROUTE_KEYS.HOME, ROUTE_KEYS.INVENTORY, ROUTE_KEYS.REPORTS, ROUTE_KEYS.ME],
    features: []
  },
  [ROLES.PURCHASE]: {
    routes: [ROUTE_KEYS.HOME, ROUTE_KEYS.PURCHASE, ROUTE_KEYS.INVENTORY, ROUTE_KEYS.REPORTS, ROUTE_KEYS.ME],
    features: [FEATURES.PURCHASE_VIEW]
  },
  [ROLES.FINANCE]: {
    routes: [ROUTE_KEYS.HOME, ROUTE_KEYS.FINANCE, ROUTE_KEYS.SALES, ROUTE_KEYS.REPORTS, ROUTE_KEYS.ME],
    features: [FEATURES.FINANCE_VIEW]
  },
  [ROLES.EMPLOYEE]: {
    routes: [ROUTE_KEYS.HOME, ROUTE_KEYS.REPORTS, ROUTE_KEYS.ME],
    features: []
  }
});
